/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abenantelutzengitasql;

/**
 *
 * @author abenante.lucia
 */
public class JPartecipazione extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JPartecipazione.class.getName());

    /**
     * Creates new form JPartecipazione
     */
    public JPartecipazione() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlSfondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCreaClasse = new javax.swing.JButton();
        btnCreaStudente = new javax.swing.JButton();
        btnCreaGita = new javax.swing.JButton();
        btnVisualizzaStudente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(667, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPnlSfondo.setBackground(new java.awt.Color(135, 197, 234));
        jPnlSfondo.setForeground(new java.awt.Color(0, 126, 249));
        jPnlSfondo.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 126, 249));
        jPanel1.setLayout(null);

        jTable2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Studente", "Gita"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(60, 70, 200, 370);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(135, 197, 234));
        jLabel1.setText("ID dello Studente e delle Gite ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 260, 25);

        jPnlSfondo.add(jPanel1);
        jPanel1.setBounds(0, 0, 340, 470);

        btnCreaClasse.setBackground(new java.awt.Color(135, 197, 234));
        btnCreaClasse.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCreaClasse.setForeground(new java.awt.Color(0, 126, 249));
        btnCreaClasse.setText("Crea Classe");
        btnCreaClasse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 126, 249), 2, true));
        jPnlSfondo.add(btnCreaClasse);
        btnCreaClasse.setBounds(390, 60, 120, 50);

        btnCreaStudente.setBackground(new java.awt.Color(135, 197, 234));
        btnCreaStudente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCreaStudente.setForeground(new java.awt.Color(0, 126, 249));
        btnCreaStudente.setText("Crea Studente");
        btnCreaStudente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 126, 249), 2, true));
        jPnlSfondo.add(btnCreaStudente);
        btnCreaStudente.setBounds(390, 160, 120, 50);

        btnCreaGita.setBackground(new java.awt.Color(135, 197, 234));
        btnCreaGita.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCreaGita.setForeground(new java.awt.Color(0, 126, 249));
        btnCreaGita.setText("Crea Gita");
        btnCreaGita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 126, 249), 2, true));
        jPnlSfondo.add(btnCreaGita);
        btnCreaGita.setBounds(390, 260, 120, 50);

        btnVisualizzaStudente.setBackground(new java.awt.Color(135, 197, 234));
        btnVisualizzaStudente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnVisualizzaStudente.setForeground(new java.awt.Color(0, 126, 249));
        btnVisualizzaStudente.setText("Visualizza Tutto");
        btnVisualizzaStudente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 126, 249), 2, true));
        btnVisualizzaStudente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizzaStudenteActionPerformed(evt);
            }
        });
        jPnlSfondo.add(btnVisualizzaStudente);
        btnVisualizzaStudente.setBounds(380, 370, 140, 50);

        getContentPane().add(jPnlSfondo);
        jPnlSfondo.setBounds(-1, -6, 680, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizzaStudenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizzaStudenteActionPerformed
        // TODO add your handling code here:
        
        java.awt.EventQueue.invokeLater(() -> new JVisualizza().setVisible(true));
    }//GEN-LAST:event_btnVisualizzaStudenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JPartecipazione().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreaClasse;
    private javax.swing.JButton btnCreaGita;
    private javax.swing.JButton btnCreaStudente;
    private javax.swing.JButton btnVisualizzaStudente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlSfondo;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
